# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ffledgling's blog
email: ffledgling [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
    Welcome to ffledgling's blog.
    This site is currently under reconstruction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.ffledgling.com" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: ffledgling
github_username: ffledgling

# Build settings
markdown: kramdown
